### PR TITLE
Added two new HttpMethods, PATCH and TRACE

### PR DESCRIPTION
**Pull request by nclarence**
I simply added two new browser api methods for the HttpMethods PATCH and TRACE.

### CODE REVIEW

**Comment by jchannon** [comment]
Thanks!

**Comment by nclarence** [comment]
Hi Jonathan,

Thanks for merging my changes into master.

I made those changes as I could really use the PATCH method in our unit
testing. Before I can do that, I need for the change to be pushed up into
Nuget. Can I please ask what the process moving forward in regards getting
the updates into Nuget?

Thanks.

-----------------

Regards,

Nathan Clarence
P: 0417 407 284
E: nclarence@gmail.com

**Comment by jchannon** [comment]
Hi,

Pushed to NuGet.

I'm not really maintaining this project much as Microsoft released their
Owin.Testing library, there's also @damianh OwinHttpMessageHandler project
which may help.

Thanks again

**Comment by nclarence** [comment]
Thanks Jonathan.

-----------------

Regards,

Nathan Clarence
P: 0417 407 284
E: nclarence@gmail.com

**Pull request merged**
